### ISSUE TITLE
After API Call, send a List of "dummy" Records that the User can select for delete/creation

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#31] opened 2020-03-05 05:58 UTC
Potential Idea: Use JSON.serialize to send a List of Objects with the important values from the call.

Data Schema:
List<Object> --> Map<String,String> (Each Map is a record that's housed in the List of Objects)
[
{Church_Account__c: "0015400000Tc4GKAAZ", School_Account__c: "0015400000SYBvyAAH", Status__c: "Potential", Id: "a0k54000009MotrAAC"}
]
https://foobarforce.wordpress.com/2014/07/25/apex-method-of-the-day-json-serialize-object/

After the rows are selected, pass the {selectedRows} back to an Apex method that will then perform DML operations.

**Comment by Julian88Tex** [comment] 2020-03-15 22:52
Close as a duplicate of #13 .

**Closed as completed by Julian88Tex** 2020-03-15 22:52 UTC
